name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies (PhotoSwipe.Blazor)
      working-directory: ./PhotoSwipe.Blazor
      run: |
        npm install
        npm run build

    - name: Install Playwright dependencies
      working-directory: ./tests
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Start PhotoSwipe Sample App
      run: |
        cd PhotoSwipe.Sample
        dotnet run --urls http://localhost:5224 &
        sleep 10
        curl --retry 10 --retry-delay 2 --retry-connrefused http://localhost:5224 || exit 1

    - name: Run Playwright tests
      working-directory: ./tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 30